version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3110:3100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/.turbo
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000
    depends_on:
      - auth-service
      - user-service
      - content-service

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000"
    volumes:
      - ./services/auth-service:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=Server=db;Database=jnetsolution;User=dev;Password=devpass;
      - JWT_SECRET=your-development-secret-key-min-32-characters-long
    depends_on:
      - db

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./services/user-service:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://dev:devpass@db:5432/jnetsolution
    depends_on:
      - db

  content-service:
    build:
      context: ./services/content-service
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./services/content-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:devpass@db:5432/jnetsolution
    depends_on:
      - db

  stock-data-service:
    build:
      context: ./services/stock-data-service
      dockerfile: Dockerfile.dev
    ports:
      - "9001:9000"
    volumes:
      - ./services/stock-data-service:/app
      - stock-data:/app/data
      - /app/.venv
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - DATA_DIRECTORY=/app/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jnetsolution
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  stock-data: