apiVersion: v1
kind: Service
metadata:
  name: n8n-nodeport
  namespace: n8n
  labels:
    app: n8n
    component: webserver
spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: 30082
      protocol: TCP
      name: n8n-ui
  selector:
    app: n8n
