name: API Service - Production
on:
  push:
    branches: [main]
    paths:
      - 'services/api-service/**'
      - '.github/workflows/api-service-main.yml'

permissions:
  contents: write

env:
  SERVICE_NAME: api-service
  SERVICE_PATH: ./services/api-service
  IMAGE_NAME: jnet-api-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
      
      - name: Install dependencies
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          uv sync
      
      - name: Run tests
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          uv run pytest tests/ -v --cov=app --cov-report=xml
      
      - name: Run linting
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          ./scripts/lint.sh

  version:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    outputs:
      semVer: ${{ steps.versioning.outputs.new-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          prefix: api-service-v
          release-branch: main

      - name: Print Version
        id: versioning
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          VERSION_NUMBER=$(echo ${{ steps.version.outputs.version }} | sed 's/^api-service-v//')
          echo "Version Number: $VERSION_NUMBER"
          echo "new-version=$VERSION_NUMBER" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: API Service Release ${{ steps.version.outputs.version }}
          body: |
            API Service Release ${{ steps.version.outputs.version }}
            
            Docker image: `${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ steps.versioning.outputs.new-version }}`
            
            ## What's Changed
            See commit history for changes included in this release.
          draft: false
          prerelease: false

  build-and-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: version
    env:
      SEMVER: ${{ needs.version.outputs.semVer }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          file: ${{ env.SERVICE_PATH }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ env.SEMVER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [version, build-and-push]
    environment:
      name: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy API Service to Cloud Run
        run: |
          gcloud run deploy api-service \
            --image docker.io/${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.semVer }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account 506487697841-compute@developer.gserviceaccount.com \
            --set-env-vars="ENVIRONMENT=production,LOG_LEVEL=INFO,API_KEY=${{ secrets.API_SERVICE_KEY }},STOCK_DATA_SERVICE_URL=${{ secrets.STOCK_DATA_SERVICE_URL }},STOCK_DATA_SERVICE_API_KEY=${{ secrets.STOCK_DATA_SERVICE_API_KEY }},VERSION=${{ needs.version.outputs.semVer }}" \
            --memory 512Mi \
            --cpu 1 \
            --port 8002
            
      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe api-service \
            --region us-central1 \
            --format 'value(status.url)')
          echo "API Service deployed to: $SERVICE_URL"
          echo "### Deployment Complete! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "API Service deployed to: $SERVICE_URL" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.version.outputs.semVer }}" >> $GITHUB_STEP_SUMMARY