name: Develop Branch Build and Push

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  GAR_REPOSITORY: jnet-site

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.changes.outputs.frontend }}
      auth-service-changed: ${{ steps.changes.outputs.auth-service }}
      user-service-changed: ${{ steps.changes.outputs.user-service }}
      content-service-changed: ${{ steps.changes.outputs.content-service }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          frontend:
            - 'frontend/**'
          auth-service:
            - 'services/auth-service/**'
          user-service:
            - 'services/user-service/**'
          content-service:
            - 'services/content-service/**'

  test-and-build:
    needs: detect-changes
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Frontend tests
    - name: Setup Node.js for Frontend
      if: needs.detect-changes.outputs.frontend-changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Frontend - Install and Test
      if: needs.detect-changes.outputs.frontend-changed == 'true'
      run: |
        npm ci
        npm run lint
        npm run build
      working-directory: frontend
    
    # Auth Service tests
    - name: Setup .NET for Auth Service
      if: needs.detect-changes.outputs.auth-service-changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Auth Service - Build and Test
      if: needs.detect-changes.outputs.auth-service-changed == 'true'
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
      working-directory: services/auth-service
    
    # User Service tests
    - name: Setup Python for User Service
      if: needs.detect-changes.outputs.user-service-changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: User Service - Install and Test
      if: needs.detect-changes.outputs.user-service-changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pytest tests/ --cov=app
      working-directory: services/user-service
    
    # Content Service tests
    - name: Setup Node.js for Content Service
      if: needs.detect-changes.outputs.content-service-changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: services/content-service/package-lock.json
        
    - name: Content Service - Install and Test
      if: needs.detect-changes.outputs.content-service-changed == 'true'
      run: |
        npm ci
        npm test
      working-directory: services/content-service

  build-and-push-images:
    needs: [detect-changes, test-and-build]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev
    
    # Build and push Frontend
    - name: Build and push Frontend Docker image
      if: needs.detect-changes.outputs.frontend-changed == 'true'
      run: |
        docker build -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/frontend:develop \
                     -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/frontend:sha-${{ github.sha }} \
                     -f frontend/Dockerfile \
                     frontend/
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/frontend:develop
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/frontend:sha-${{ github.sha }}
    
    # Build and push Auth Service
    - name: Build and push Auth Service Docker image
      if: needs.detect-changes.outputs.auth-service-changed == 'true'
      run: |
        docker build -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/auth-service:develop \
                     -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/auth-service:sha-${{ github.sha }} \
                     -f services/auth-service/Dockerfile \
                     services/auth-service/
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/auth-service:develop
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/auth-service:sha-${{ github.sha }}
    
    # Build and push User Service
    - name: Build and push User Service Docker image
      if: needs.detect-changes.outputs.user-service-changed == 'true'
      run: |
        docker build -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/user-service:develop \
                     -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/user-service:sha-${{ github.sha }} \
                     -f services/user-service/Dockerfile \
                     services/user-service/
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/user-service:develop
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/user-service:sha-${{ github.sha }}
    
    # Build and push Content Service
    - name: Build and push Content Service Docker image
      if: needs.detect-changes.outputs.content-service-changed == 'true'
      run: |
        docker build -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/content-service:develop \
                     -t ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/content-service:sha-${{ github.sha }} \
                     -f services/content-service/Dockerfile \
                     services/content-service/
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/content-service:develop
        docker push ${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/content-service:sha-${{ github.sha }}