name: General CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Check Docker build context
        run: |
          echo "Checking if all Dockerfiles exist..."
          test -f frontend/Dockerfile

  script-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh

      - name: Validate scripts syntax
        run: |
          for script in scripts/*.sh; do
            bash -n "$script"
          done