name: Stock Data Service CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'services/stock-data-service/**'
      - '.github/workflows/stock-data-service.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'services/stock-data-service/**'
      - '.github/workflows/stock-data-service.yml'

permissions:
  contents: write

env:
  SERVICE_NAME: stock-data-service
  SERVICE_PATH: ./services/stock-data-service
  IMAGE_NAME: jnet-stock-data-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
      
      - name: Install dependencies
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          uv sync
      
      - name: Check code formatting
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          uv run black --check .
      
      - name: Run tests
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          uv run pytest tests/ -v --cov=app --cov-report=xml

  version:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    outputs:
      semVer: ${{ steps.versioning.outputs.new-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          prefix: stock-data-service-v
          release-branch: main

      - name: Print Version
        id: versioning
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          VERSION_NUMBER=$(echo ${{ steps.version.outputs.version }} | sed 's/^stock-data-service-v//')
          echo "Version Number: $VERSION_NUMBER"
          echo "new-version=$VERSION_NUMBER" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Stock Data Service Release ${{ steps.version.outputs.version }}
          body: |
            Stock Data Service Release ${{ steps.version.outputs.version }}
            
            Docker image: `${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ steps.versioning.outputs.new-version }}`
            
            ## What's Changed
            See commit history for changes included in this release.
          draft: false
          prerelease: false

  build-and-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: version
    env:
      SEMVER: ${{ needs.version.outputs.semVer }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          file: ${{ env.SERVICE_PATH }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ env.SEMVER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [version, build-and-push]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy Stock Data Service to Cloud Run
        run: |
          gcloud run deploy stock-data-service \
            --image docker.io/${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.semVer }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account 506487697841-compute@developer.gserviceaccount.com \
            --set-env-vars="ENVIRONMENT=production,LOG_LEVEL=INFO,GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }},GCS_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},API_KEY=${{ secrets.STOCK_DATA_SERVICE_API_KEY }},VERSION=${{ needs.version.outputs.semVer }}" \
            --memory 512Mi \
            --cpu 1 \
            --port 9000
            
      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe stock-data-service \
            --region us-central1 \
            --format 'value(status.url)')
          echo "Stock Data Service deployed to: $SERVICE_URL"
          echo "### Deployment Complete! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Stock Data Service deployed to: $SERVICE_URL" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ needs.version.outputs.semVer }}" >> $GITHUB_STEP_SUMMARY

  build-develop:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.SERVICE_PATH }}
          file: ${{ env.SERVICE_PATH }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:develop
            ${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:develop-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-develop:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build-develop
    environment:
      name: development
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Deploy Stock Data Service to Cloud Run (Development)
        run: |
          gcloud run deploy stock-data-service-develop \
            --image docker.io/${{ secrets.DOCKER_USERNAME || 'stevenjiangnz' }}/${{ env.IMAGE_NAME }}:develop-${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account 506487697841-compute@developer.gserviceaccount.com \
            --set-env-vars="ENVIRONMENT=development,LOG_LEVEL=DEBUG,GCS_BUCKET_NAME=${{ secrets.DEV_GCS_BUCKET_NAME || 'jnet-stock-data-dev' }},GCS_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},API_KEY=${{ secrets.DEV_STOCK_DATA_SERVICE_API_KEY || 'dev-api-key' }}" \
            --memory 512Mi \
            --cpu 1 \
            --port 9000
            
      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe stock-data-service-develop \
            --region us-central1 \
            --format 'value(status.url)')
          echo "Stock Data Service (Development) deployed to: $SERVICE_URL"
          echo "### Development Deployment Complete! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "Stock Data Service deployed to: $SERVICE_URL" >> $GITHUB_STEP_SUMMARY